

title: Mysiar's notes
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mysiar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mysiar71
github_username:  mysiar

# Build settings
theme: jekyll-theme-so-simple
#theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-feed

remote_theme: "mmistakes/so-simple-theme@3.2.0"

skin: "/assets/css/skins/default.css"


date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
#google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"

markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Site Author
author:
  name: Piotr Synowiec
  picture: https://en.gravatar.com/userimage/96815547/aacfdefdb0c12bc053b46970969b14ed.jpeg
  email:
  twitter: mysiar71
  links:
    - title: Twitter
      url: https://twitter.com/mysiar71
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/mysiar71
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/mysiar
      icon: fab fa-github-square
# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/mysiar71
    icon: fab fa-twitter-square
#  - title: Instagram
#    url: https://instagram.com/mysiar71
#    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/mysiar
    icon: fab fa-github-square
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
